let lang = "en";
const translate = {
	en: {
		firstname: "Firstname",
		lastname: "Lastname",
		idnumber: "ID Number",
		email: "Email",
		phone: "Phone",
		address: "Address",
		city: "City",
		state: "State",
		zip: "Zip",
		country: "Country",
		send: "Send",
		login: "Login",
		logout: "Logout",
		register: "Register",
		username: "Username",
		password: "Password",
		confirm: "Confirm",
		forgot: "Forgot",
		remember: "Remember",
		me: "Me",
		profile: "Profile",
		create: "Create",
		confirmEmail: "Confirm email",
		sendProfile: "Send profile",
		resend: "Resend",
		next: "Next",
		back: "Back",
		cancel: "Cancel",
		save: "Save",
		edit: "Edit",
		delete: "Delete",
		search: "Search",
		confirmCode: "Enter the confirmation code we sent to",
		homePageMessage: "Create profile easily and securely share your information with others.",
		haveProfile: "You allready have profile?",
		enterCode: "Enter confirm code",
		getProfile: "Get your profile",
		createProfile: "Create profile",
		enterEmail: "Enter your email",
		createAccount: "Create account",
		or: "Or",
		setYourPassword: "Set your password",
		eneterPassword: "Enter password",
		setPassword: "Set password",
		confirmCodeTitle: "Confirm code",
		enterUsername: "Enter username",
		createYourProfile: "Create your profile",
		loading: "Loading...",
		sendYourInfo: "Send your information",
		zipcode: "Zipcode",
		editProfile: "Edit profile",
		myProfile: "My profile",
		logout: "Logout",
		allNotifications: "All notifications",
		noNotifications: "No notifications",
		notifications: "Notifications",
		fistQRInfo: "Who scan this QR code will send his information to you.",
		secoundQRInfo: `Any one who scan this QR code will see your information. After code expire no one can't see your infomation.`,
	},
	de: {
		firstname: "Vorname",
		lastname: "Nachname",
		idnumber: "ID Nummer",
		email: "Email",
		phone: "Telefon",
		address: "Adresse",
		city: "Stadt",
		state: "Staat",
		zip: "Postleitzahl",
		country: "Land",
		send: "Senden",
		login: "Anmelden",
		logout: "Abmelden",
		register: "Registrieren",
		username: "Benutzername",
		password: "Passwort",
		confirm: "Bestätigen",
		forgot: "Vergessen",
		remember: "Erinnern",
		me: "Ich",
		profile: "Profil",
		create: "Erstellen",
		confirmEmail: "Email bestätigen",
		sendProfile: "Profil senden",
		resend: "Erneut senden",
		next: "Nächster",
		back: "Zurück",
		cancel: "Abbrechen",
		save: "Speichern",
		edit: "Bearbeiten",
		delete: "Löschen",
		search: "Suche",
		confirmCode: "Geben Sie den Bestätigungscode ein, den wir an",
		homePageMessage: "Erstellen Sie ein Profil und teilen Sie Ihre Informationen sicher mit anderen.",
		haveProfile: "Sie haben bereits ein Profil?",
		enterCode: "Bestätigungscode eingeben",
		getProfile: "Erhalten Sie Ihr Profil",
		createProfile: "Profil erstellen",
		enterEmail: "Geben Sie Ihre E-Mail-Adresse ein",
		createAccount: "Konto erstellen",
		or: "Oder",
		setYourPassword: "Setzen Sie Ihr Passwort",
		eneterPassword: "Passwort eingeben",
		setPassword: "Passwort festlegen",
		confirmCodeTitle: "Bestätigungscode",
		enterUsername: "Benutzernamen eingeben",
		createYourProfile: "Erstellen Sie Ihr Profil",
		loading: "Wird geladen...",
		sendYourInfo: "Senden Sie Ihre Informationen",
		zipcode: "Postleitzahl",
		editProfile: "Profil bearbeiten",
		myProfile: "Mein Profil",
		logout: "Abmelden",
		allNotifications: "Alle Benachrichtigungen",
		noNotifications: "Keine Benachrichtigungen",
		notifications: "Benachrichtigungen",
		fistQRInfo: "Jeder, der diesen QR-Code scannen, wird seine Informationen an Sie senden.",
		secoundQRInfo:
			"Jeder, der diesen QR-Code scannen, wird Ihre Informationen sehen.\n Diese Informationen werden nicht in unserem Server gespeichert.",
	},
};

export const setLang = (newLang) => {
	lang = newLang;
};

export default translate[lang];
